# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from PyQt6.QtWidgets import QApplication, QDialog, QVBoxLayout, QLabel
from PyQt6.QtGui import QPixmap


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800,600)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(70, 30, 280, 340))
        self.frame.setStyleSheet("*{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QFrame#frame{\n"
"    border-radius:30px;\n"
"    border-image: url(:/new/prefix3/aaa.jpg);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 281, 341))
        self.frame_2.setStyleSheet("*{\n"
"    border-radius:30px;\n"
"    background-color: rgba(117, 117, 127, 120);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 50, 240, 280))
        self.label.setStyleSheet("*{\n"
"    border-radius:30px;\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgba(255, 248, 175, 180);\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 211, 31))
        self.label_2.setStyleSheet("*{\n"
"    background:transparent;\n"
"    \n"
"    color: rgba(85, 0, 127, 200);\n"
"    font: 15pt \"等线\";\n"
"}")
        self.label_2.setObjectName("label_2")
        self.lineEdit_username = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_username.setGeometry(QtCore.QRect(60, 120, 161, 21))
        self.lineEdit_username.setStyleSheet("*{\n"
"    font: 9pt \"Microsoft YaHei UI\";\n"
"    background:transparent;\n"
"    border:none;\n"
"    border-bottom:1px solid rgba(85, 0, 127, 200);\n"
"    \n"
"    color: rgba(85, 0, 127, 255);\n"
"}")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_password.setGeometry(QtCore.QRect(60, 170, 161, 21))
        self.lineEdit_password.setStyleSheet("*{\n"
"    background:transparent;\n"
"    border:none;\n"
"    border-bottom:1px solid rgba(85, 0, 127, 200);\n"
"    \n"
"    color: rgba(85, 0, 127, 255);\n"
"}")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_login = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_login.setGeometry(QtCore.QRect(80, 240, 121, 41))
        self.pushButton_login.setStyleSheet("\n"
"/* 基础样式 */\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgba(170, 170, 255, 180);\n"
"    border: 2px solid rgba(120, 120, 220, 200);\n"
"    color: #333;\n"
"    font: 700 12pt \"等线\";\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background-color: rgba(150, 150, 240, 200);\n"
"}\n"
"\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(140, 140, 230, 200);\n"
"    padding: 9px 17px 7px 15px;\n"
"}")
        self.pushButton_login.setObjectName("pushButton_login")
        self.checkBox_remember = QtWidgets.QCheckBox(parent=self.frame_2)
        self.checkBox_remember.setGeometry(QtCore.QRect(110, 200, 141, 20))
        self.checkBox_remember.setStyleSheet("* {\n"
"    spacing: 2px; /* 文本和指示器之间的间距 */\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    border-radius:10px;\n"
"    font-size: 10px;\n"
"    background-color: rgba(177, 177, 177, 180);\n"
"    color: rgba(114, 87, 127, 255);\n"
"}\n"
"\n"
"")
        self.checkBox_remember.setObjectName("checkBox_remember")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(50, 290, 191, 20))
        self.label_3.setStyleSheet("*{\n"
"    background:transparent;\n"
"    \n"
"    font: 9pt \"等线\";\n"
"    color: rgba(114, 87, 227, 255);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.toolButton1 = QtWidgets.QToolButton(parent=self.frame_2)
        self.toolButton1.setGeometry(QtCore.QRect(210, 10, 20, 18))
        self.toolButton1.setStyleSheet("*{\n"
"    background-color: rgba(255, 255, 255, 180);\n"
"    border-radius: 6px;\n"
"}")
        self.toolButton1.setObjectName("toolButton1")
        self.toolButton_2 = QtWidgets.QToolButton(parent=self.frame_2)
        self.toolButton_2.setGeometry(QtCore.QRect(240, 10, 20, 18))
        self.toolButton_2.setStyleSheet("*{\n"
"    background-color: rgba(255, 255, 255, 180);\n"
"    border-radius: 6px;\n"
"}")
        self.toolButton_2.setObjectName("toolButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Your Flower Spring Out!"))
        self.lineEdit_username.setPlaceholderText(_translate("Dialog", "User Name:"))
        self.lineEdit_password.setPlaceholderText(_translate("Dialog", "Password:"))
        self.pushButton_login.setText(_translate("Dialog", "Log In"))
        self.checkBox_remember.setText(_translate("Dialog", "Remember your password"))
        self.label_3.setText(_translate("Dialog", "Forget your password or username?"))
        self.toolButton1.setText(_translate("Dialog", "—"))
        self.toolButton_2.setText(_translate("Dialog", "X"))

class MyDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        # 创建 Ui_Dialog 实例
        self.ui = Ui_Dialog()
        # 调用 setupUi 方法设置界面
        self.ui.setupUi(self)

if __name__=="__main__":
        app = QApplication(sys.argv)
        dialog = MyDialog()
        dialog.show()
        sys.exit(app.exec())
